// React Imports
import { useState } from 'react'

// NextJs Imports
import Head from 'next/head'
import Image from "next/legacy/image";

// MUI Imports
import { Box, Container, Paper, Tab, Tabs, Typography, Stack, Avatar, Button, Grid, Drawer, Divider, IconButton } from '@mui/material'
import { useTheme } from '@mui/material/styles'

// Icons
import LinkIcon from '@mui/icons-material/Link';
import ShoppingBasketOutlinedIcon from '@mui/icons-material/ShoppingBasketOutlined';
import MicNoneOutlinedIcon from '@mui/icons-material/MicNoneOutlined';
import PhonelinkRingOutlinedIcon from '@mui/icons-material/PhonelinkRingOutlined';
import LibraryMusicOutlinedIcon from '@mui/icons-material/LibraryMusicOutlined';
import EventAvailableOutlinedIcon from '@mui/icons-material/EventAvailableOutlined';
import ExpandMoreOutlinedIcon from '@mui/icons-material/ExpandMoreOutlined';
import CloseOutlinedIcon from '@mui/icons-material/CloseOutlined';

// Project Imports
import thumbnail from '../../../../../public/assets/pictures/thumbnail.jpg'

// Components
import MobileNavigationLayout from '@/layout/mobile/MobileNavigationLayout'
import TabStreamingLinks from '@/components/reusableComponents/TabStreamingLinks';
import TabProductCard from '@/components/reusableComponents/TabProductCard';
import TabLyricsCard from '@/components/reusableComponents/TabLyricsCard';
import TabSkizaCards from '@/components/reusableComponents/TabSkizaCards';
import TabAlbumCard from '@/components/reusableComponents/TabAlbumCard';
import TabEventsCards from '@/components/reusableComponents/TabEventsCards';
import MoreVideos from '@/components/reusableComponents/MoreVideos';
import Copyright from '@/components/reusableComponents/Copyright';




const CurrentVideo = ({ setIsDarkMode, isDarkMode }) => {
    const theme = useTheme()
    const [tabPosition, setTabPosition] = useState(0)
    const [showSongDetails, setShowSongDetails] = useState(false)
    const [showMoreVideos, setShowMoreVideos] = useState(false)

    const handleChange = (event, newValue) => {
        setTabPosition(newValue);
      };


  return (
    <>
    <MobileNavigationLayout setIsDarkMode={setIsDarkMode} isDarkMode={isDarkMode} >
        <Head>
          <title>Buy Dukaflani branded hoodie - ksh.3,500 | Wakadinali</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box sx={{backgroundColor: theme.myColors.myBackground, minHeight: '100vh', paddingTop: 5, paddingBottom: 10}}>
            <Box sx={{position: 'sticky', top: 50, zIndex: 99}} >
                <Box sx={{backgroundColor: 'black', width: '100%'}}>
                    <Container disableGutters maxWidth='sm'>
                        <Box sx={{backgroundColor: 'yellow', width: '100%', paddingTop: '56.25%'}}>video</Box>
                    </Container>
                </Box>
                <Paper square sx={{display: 'flex', justifyContent: 'center'}}>
                    <Tabs
                        variant="scrollable"
                        scrollButtons
                        allowScrollButtonsMobile
                        value={tabPosition}
                        onChange={handleChange}
                        sx={{}}
                    >
                        <Tab icon={<LinkIcon />} iconPosition='start' label="Links" />
                        <Tab icon={<ShoppingBasketOutlinedIcon />} iconPosition='start' label="Shop" />
                        <Tab icon={<MicNoneOutlinedIcon />} iconPosition='start' label="Lyrics" />
                        <Tab icon={<PhonelinkRingOutlinedIcon />} iconPosition='start' label="Skiza Tunes" />
                        <Tab icon={<LibraryMusicOutlinedIcon />} iconPosition='start' label="Album" />
                        <Tab icon={<EventAvailableOutlinedIcon />} iconPosition='start' label="Events" />
                    </Tabs>
                </Paper>
            </Box>
            <Container sx={{paddingTop: 3}} maxWidth='sm'>
                <Stack spacing={1.5}>
                    <Box onClick={() => setShowSongDetails(true)}>
                        <Typography gutterBottom sx={{lineHeight: 1}} component='h1' variant='h6'>SongTitle goes here and should not be trancated in anyway shape or form</Typography>
                        <Stack sx={{display: 'flex', alignItems: 'center', justifyContent: 'start'}} direction='row' spacing={1}>
                            <Typography sx={{color: '#1976d2'}} variant='button'>Gengetone</Typography>
                            <Typography variant='caption'>3.4m views</Typography>
                            <Typography variant='caption'>6 months ago</Typography>
                            <Typography variant='subtitle2'>more...</Typography>
                        </Stack>
                    </Box>
                    <Box sx={{display: 'flex', alignItems: 'center', justifyContent: 'start'}}>
                        <Avatar  src='/assets/pictures/wakadinali_profile.jpg' />
                        <Box sx={{paddingX: 1, display: 'flex', alignItems: 'center', justifyContent: 'start'}}>
                            <Typography className="line-clamp-1 line-clamp" variant='subtitle2'>Diamond Platnumz</Typography>
                        </Box>
                        <Box sx={{flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'start', paddingX: 1}}>
                            <Typography variant='caption'>2.3m</Typography>
                        </Box>
                        <IconButton>
                            <FavoriteBorderOutlinedIcon fontSize='small' />
                        </IconButton>
                    </Box>
                    <Paper onClick={() => setShowMoreVideos(true)} variant='outlined' sx={{ backgroundColor: theme.myColors.myBackground, padding: 1 }}>
                        <Stack>
                            <Typography variant='subtitle2'>MORE VIDEOS:</Typography>
                            <Grid direction='row' container columnSpacing={1}>
                                <Grid xs={4} item>
                                    <Box sx={{ width: '100%', height: '56.25%', borderRadius: 2, position: "relative", cursor:'pointer'}}>
                                        <Image 
                                            src={thumbnail} 
                                            layout='responsive'
                                            alt='video title (Official Video)'
                                            style={{borderRadius: 6}}
                                            />
                                    </Box>
                                </Grid>
                                <Grid xs={7} item>
                                    <Stack>
                                        <Typography sx={{lineHeight: 1}} className="line-clamp-2 line-clamp" variant='subtitle2'>SongTitle goes here and should not be trancated in anyway shape or form</Typography>
                                        <Typography className="line-clamp-1 line-clamp" variant='caption'>Diamond Platnumz</Typography>
                                    </Stack>
                                </Grid>
                                <Grid xs={1} item>
                                <ExpandMoreOutlinedIcon />
                                </Grid>
                            </Grid>
                        </Stack>
                    </Paper>
                    <Box sx={{paddingTop: 2}}>
                        {
                            {
                                0: <TabStreamingLinks/>,
                                1: <TabProductCard/>,
                                2: <TabLyricsCard/>,
                                3: <TabSkizaCards/>,
                                4: <TabAlbumCard/>,
                                5: <TabEventsCards/>,
                            }[tabPosition]
                        }
                    </Box>
                </Stack>
            </Container>
            <Box sx={{padding: 1, textAlign: 'center'}}>
                {
                    {
                        0: <Typography variant='caption'>Terms & Conditions Apply</Typography>,
                        1: <Typography variant='caption'>Sold by Dukaflani</Typography>,
                        2: <Typography variant='caption'>&copy; {new Date().getFullYear()} Wakadinali. All rights Reserved</Typography>,
                        3: <Typography variant='caption'>Terms & Conditions Apply</Typography>,
                        4: <Typography variant='caption'>&copy; {new Date().getFullYear()} Wakadinali. All rights Reserved</Typography>,
                        5: <Typography variant='caption'>Terms & Conditions Apply</Typography>,
                    }[tabPosition]
                }
            </Box>
        </Box>
    </MobileNavigationLayout>

    {/* Song Details Drawer */}
    <Box> 
        <Drawer
             open={showSongDetails}
             onClose={() => setShowSongDetails(false)}
             anchor='bottom'
        >
            <Box sx={{ backgroundColor: theme.myColors.myBackground}}>
                <Container sx={{height: '60vh'}} maxWidth='sm'>
                    <Stack spacing={2}>
                        <Box sx={{paddingTop: 3, position: 'sticky', top: 0, backgroundColor: theme.myColors.myBackground, zIndex: 99}}>
                            <Box sx={{display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
                                <Typography variant='subtitle1'>INFO:</Typography>
                                <Box onClick={() => setShowSongDetails(false)}>
                                    <CloseOutlinedIcon />
                                </Box>
                            </Box>
                            <Divider/>
                        </Box>
                        <Box>
                            <Box sx={{display: 'flex', alignItems: 'center', justifyContent: 'space-evenly'}}>
                                <Box sx={{textAlign: 'center'}}>
                                    <Typography variant='subtitle2'>282,345,674</Typography>
                                    <Typography variant='caption'>views</Typography>
                                </Box>
                                <Box sx={{textAlign: 'center'}}>
                                    <Typography variant='subtitle2'>3.5k</Typography>
                                    <Typography variant='caption'>likes</Typography>
                                </Box>
                                <Box sx={{textAlign: 'center'}}>
                                    <Typography variant='subtitle2'>Fri, 23 Jun 2023</Typography>
                                    <Typography variant='caption'>added</Typography>
                                </Box>
                            </Box>
                        </Box>
                        <Divider/>
                        <Box>
                            <Typography variant='body2'>Song description goes here</Typography>
                        </Box>
                    </Stack>
                    {/* Copyright */}
                    <Box>
                        <Copyright/>
                    </Box>
                </Container>
            </Box>
        </Drawer>
    </Box>

    {/* Show More Videos Drawer */}
    <Box>
        <Drawer
             open={showMoreVideos}
             onClose={() => setShowMoreVideos(false)}
             anchor='bottom'
        >
            <Box sx={{ backgroundColor: theme.myColors.myBackground}}>
                <Container sx={{ height: '60vh'}} maxWidth='sm'>
                    <Stack>
                        <Box sx={{paddingTop: 3, position: 'sticky', top: 0, backgroundColor: theme.myColors.myBackground, zIndex: 99}}>
                            <Box sx={{display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
                                <Typography variant='subtitle1'>MORE VIDEOS:</Typography>
                                <Box onClick={() => setShowMoreVideos(false)}>
                                    <CloseOutlinedIcon />
                                </Box>
                            </Box>
                            <Divider/>
                        </Box>
                        <Box>
                            <MoreVideos/>
                        </Box>
                        {/* Copyright */}
                        <Box>
                            <Copyright/>
                        </Box>
                    </Stack>
                </Container>
            </Box>
        </Drawer>
    </Box>
    </>
  )
}

export default CurrentVideo